### ISSUE TITLE
Upload to Dropbox seems to fail

### ISSUE THREAD

**Issue by jyucsiro** [ausecocloud/ecocloud#2]
Tried "Save to Dropbox" in ecocloud compute. 

It recognises my Dropbox account and I can select the folder to save to. Upload starts but seems to fail. Screenshot:
![image](https://user-images.githubusercontent.com/4723726/43301763-746073fa-91aa-11e8-8ca4-6ab790b7cda6.png)

**Comment by gweis** [comment]
Seems like it is hitting the wrong url which redirects to the nbconvert endpoint?

https://jupyter.ecocloud.org.au/user/2565d4e0-3dca-46a1-8420-32168111efb2/notebooks/Transform%20Licences.ipynb"

Uncaught exception GET /user/2565d4e0-3dca-46a1-8420-32168111efb2/nbconvert/ipynb/Transform%20Licences.ipynb?download=true

**Comment by gweis** [comment]
This particular issues is fixed, and dropbox upload works again.

One big issues is left though. Currently the js UI is only able to upload files from the notebook root folder. (will be fixed in another issue)
