### ISSUE TITLE
Connect project storage to servers

### ISSUE THREAD

**Issue by hoylen** [ausecocloud/ecocloud#21]
Make the project storage accessible to the Jupyter server. This would also require the user to be able to select which project they want to use (if they have more than one) when they launch the server.

Currently, scripts and notebooks are stored in _/home/jovyian_, which is the _server temporary storage_ since it is lost when the server is terminated.

**Comment by gweis** [comment]
This is done. Initial version of storage controller is deployed, but I do expect issues with it. I think we should close this issue, and track specific problems in separate issues. (maybe tagged appropriately, or otherwise grouped by or assigned to specific components)
