### ISSUE TITLE
Fix account details page

### ISSUE THREAD

**Issue by hoylen** [ausecocloud/ecocloud#22]
The _Account details_ page (i.e. the form you get when you click on your name in the top-right of the page and select "Account") needs checking and fixing.

Change the title from "User details..." to "Account details...".

If the person has signed in using AAF, there should not be any ability to change their name, email or username. Those attributes come from the AAF login and the _ecocloud Platform_ should not be maintaining its own/separate copy of them.

Note: the information provided by the AAF login can change the next time the person signs in. For example, we have seen this happen when a person has changed their maiden name: the university changed their surname and email address on the login.

The _Accounts details_ page might be more useful when we have local logins, but right now there is probably nothing very useful to put on it. Perhaps show read-only values from their AAF login?

**Comment by manhinli** [comment]
Because we can't differentiate between those who have signed in via AAF vs local in order to do this, we have decided to simply remove the component for now as its functionality is very limited at this point.

**Comment by hoylen** [comment]
Good.
