### ISSUE TITLE
Fix bug on the server page, that fails when you first choose an option?

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#27]
Error message: Error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Screenshot attached.
<img width="830" alt="screen shot 2018-08-22 at 10 26 09 am" src="https://user-images.githubusercontent.com/14067061/44435952-db52b000-a5f5-11e8-906d-b378eea74b6b.png">

**Comment by hoylen** [comment]
Gerhard said this is a "known issue".

I have documented the work around in the [using Jupyter Notebooks](http://support.ecocloud.org.au/support/solutions/articles/6000200389-using-jupyter-notebooks) support article... but that assumes users read the article before trying to launch!

**Comment by gweis** [comment]
fix deployed
