### ISSUE TITLE
Broken links to server on dashboard

### ISSUE THREAD

**Issue by hoylen** [ausecocloud/ecocloud#29]
On the Dashboard, when there is a server running, clicking on the name link "server" or "Open" button opens a new tab with a dialog box that says "Please use a different workspace" and asks for a URI friendly workspace name (whatever that is).

**Comment by gweis** [comment]
I have no idea what these workspaces are, but the message also says:

'This workspace is already in use in another JupyterLab window. Please enter another workspace name.'

Not sure what the solution here is.

**Comment by hoylen** [comment]
> Not sure what the solution here is.

Remove the links, so the user doesn't get asked things they haven't got a hope of understanding?

Except, of course, there doesn't seem to be a way for the user to get back to their running server (not even to terminate it).

**Comment by gweis** [comment]
For me this message only comes up if I have a lab frontend open in another tab. When I close that tab, this link works.

**Comment by hoylen** [comment]
Me too.

Good that is the workaround. I'll document it.
