### ISSUE TITLE
Size of available project storage needs clarification

### ISSUE THREAD

**Issue by hoylen** [ausecocloud/ecocloud#30]
How much storage is available to an account in ecocloud Projects?

The dashboard shows "9.3 GB" (which seems a strange amount). Also, is that in gigabytes (1000^4) or gibibytes (1024^4) -- if the later, it should say 9.3 GiB for improved clarity.

We need to know for the documentation, which currently says users get 10 GiB. That is liable to cause confusion, or upset users, if they then see they got 9.3 instead of 10. We should either fix either/both numbers so they match, or remove any statements about the available size from the documentation.

**Comment by sarahrichmond** [comment]
@hoylen can you make sure you tag @gweis when asking these questions? And also assign the task to someone (if unsure assign to Gerhard and he can reassign if needed). It will make sure things don't go unanswered.

**Comment by manhinli** [comment]
The API currently returns `10000000000` as the value (presumably in bytes), so a decision will need to be made on how this should be presented in terms of units.

**Comment by sarahrichmond** [comment]
Preferably it should just say 10GB - I think that's what our users will understand the most.

**Comment by hoylen** [comment]
I've changed the documentation to say "10 GB" (where 1 GB is 10^12 bytes). The dashboard needs to divide by 10^12 instead of 2^40 to match.

**Comment by hoylen** [comment]
Completed:
- The dashboard is now reporting 10.0 GB; and
- The documentation now says the same thing.
