### ISSUE TITLE
Enable local user sign up and login

### ISSUE THREAD

**Issue by gweis** [ausecocloud/ecocloud#34]
Configure Keycloak  to allow for logal user sign up and login. (what workflow do we want here?)

Once we know how the UI flow will be, we have to theme up keycloak as well.

**Comment by sarahrichmond** [comment]
@gweis can you work with @manhinli on this one today?

**Comment by manhinli** [comment]
What do we need to consider for local user account registration? Currently we have:
* full name
* username
* email
* password

Current workflow would be:
1. Hit "Sign in" to get to sign in page
2. Click "Register" (or equivalent link)
3. Fill form
4. Submit form; user is redirected to ecocloud application as usual

If that's sufficient, then all we have to do is update small bits of the interface, and flick the switch because most of it is already handled in Keycloak.

**Comment by sarahrichmond** [comment]
This sounds good @manhinli and I think that's sufficient.

I would suggest having no 'username' but instead using only email. We've had so many issues with people forgetting their user name. I often think it's easier to use their email as a username. What are your thoughts?

**Comment by hoylen** [comment]
> 1. Hit "Sign in" to get to sign in page

Can we get rid of this step, by automatically redirecting them to the sign in page if they are not already signed in? See https://github.com/ausecocloud/ecocloud/issues/16

> I would suggest having no 'username' but instead using only email.

Getting people to pick their own username does cause problems.

> full name

Break that out into family name and given name? So we can sort lists by surname, if we need to.

> allow for local user sign up and login

This ticket overrides https://github.com/ausecocloud/ecocloud/issues/7 -- close that other issue?

**Comment by manhinli** [comment]
I agree - usernames can be forgotten. Because we don't really use the usernames in other ways (like identifying messages in a forum with a username) we can simplify it without too much hassle.

This can be configured easily in Keycloak with the "email as username" option.

**Comment by manhinli** [comment]
> Can we get rid of this step, by automatically redirecting them to the sign in page if they are not already signed in? See #16

My preliminary attempts a while back encountered an infinite redirect loop issue, so while it's certainly another click at the moment, I'll need to spend some time figuring out which part of that authentication handoff is causing the redirect loop.

> Break that out into family name and given name? So we can sort lists by surname, if we need to.

I'll need to check how Keycloak handles that information.

**Comment by manhinli** [comment]
This is how it looks like at the moment (this was already in, but not yet enabled):

![image](https://user-images.githubusercontent.com/3337903/44636855-3cf98c80-a9f1-11e8-97b7-4e74b820707d.png)

> Break that out into family name and given name? So we can sort lists by surname, if we need to.

Refer to above image; we already do that.

**Comment by hoylen** [comment]
1. Use "Family name" or "Surname" instead of "last", since the order depends on culture (e.g. Asian names write the family name first). Replace "First name" with another term too.

2. And no "Username" as mentioned already.

3. "Back to sign in" instead of "Back to login".

4. Do we want them to agree with some terms and conditions before proceeding?

**Comment by manhinli** [comment]
> Use "Family name" or "Surname" instead of "last", since the order depends on culture (e.g. Asian names write the family name first). Replace "First name" with another term too.

If you are considering internationalisation, I would suggest that we go for single fields for names [[1]](https://www.w3.org/International/questions/qa-personal-names). Names are difficult to really box into something like [first] [last] anyway, regardless of how you label them. 

But if you still want 2 fields, then generally it'll be "given name" and "surname".

> Do we want them to agree with some terms and conditions before proceeding?

Do we have any?

**Comment by sarahrichmond** [comment]
@manhinli 

I think "given name" and "surname" works.

Yes, they will tick a box to indicate that they agree to the Terms of Use (same with the AAF log in). We have a draft of these, but waiting for them to go through legal at QCIF. Probably leave it out for now, and we can add it in when we have them published.

The users should have to tick the Terms of Use box each time they log in.

**Comment by manhinli** [comment]
The minor UI/stylistic changes have been done under ausecocloud/keycloak_theme/pull/1.

I've also used the term "family name" instead of "surname".

**Comment by manhinli** [comment]
As for configuration of Keycloak - once the theme changes have been merged in, the administrator (@gweis?) will then need to enable local account registration and change the identifier to be email-only.

**Comment by manhinli** [comment]
@gweis Note that the "base URL" for the application in Keycloak ("workspaceapp") must be set or one of the links in a "You are already signed in" page will be broken.

**Comment by gweis** [comment]
We also want a cpatcha there, otherwise we will see robots creating 1000s of accounts.

Keycloak supports Google's reCaptcha out of the box.

**Comment by gweis** [comment]
done
