### ISSUE TITLE
User friendly way to terminate a Jupyter server

### ISSUE THREAD

**Issue by hoylen** [ausecocloud/ecocloud#35]
Provide a user friendly way to terminate a running Jupyter server.

Currently, the user has to go to the browser's URL field and manually change the JupyterLab URL from one ending in "/lab" to "/tree". And the URL might have query parameters, making it trickier for novice users to edit.

**Comment by gweis** [comment]
There is a menu item in the lab interface "Hub", that brings you back to the control panel.

**Comment by hoylen** [comment]
Great. I'll update the documentation to use that.
