### ISSUE TITLE
Change Freshdesk theme

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#36]
Download theme zip file here - https://support.freshdesk.com/support/discussions/topics/15989

Follow instructions here to install new theme to ecocloud support portal - https://support.freshdesk.com/support/solutions/articles/64344-how-to-use-a-ready-made-freshtheme

**Comment by hoylen** [comment]
I've hacked the "Clear Support" theme to make it look like the app.ecocloud.org.au pages.
It is not perfect, but we can revisit it once an improved ecocloud theme has been created for use across all three sites (i.e. the ecocloud Platform, FreshDesk and WordPress).
