### ISSUE TITLE
Add 'alpha' tag to the ecocloud logo and add it to application

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#37]
Replace existing logo on ecocloud app, to new one with an 'alpha' tag on it.

Source files (illustrator) for the logo can be found here - https://drive.google.com/open?id=1yKTWZjA8kdfyz3-RswWOWo5-c6MWxAvl

**Comment by manhinli** [comment]
How would you like the "alpha" tag to appear and be located?

For example:
* over the logo icon, text/wordmark, both?
* size?
* font and colour?

**Comment by sarahrichmond** [comment]
@manhinli as the UI designer I am happy to take your advice.

Have attached an image of how we do it for BCCVL. We could take a similar approach, but happy to see if you have other ideas.

ecocloud font is Cabin.
<img width="216" alt="screen shot 2018-08-27 at 3 53 01 pm" src="https://user-images.githubusercontent.com/14067061/44642965-0b44ed80-aa12-11e8-9ca3-dfce3b0a7412.png">

**Comment by manhinli** [comment]
I'll play around then 😄

**Comment by manhinli** [comment]
I've shifted the text up slightly and placed the alpha text underneath. What do you think?

![image](https://user-images.githubusercontent.com/3337903/44643124-adfd6c00-aa12-11e8-8491-815b8d50649a.png)

**Comment by sarahrichmond** [comment]
Looks great! Happy to go ahead with that.
