### ISSUE TITLE
Server terminate button on dashboard does not work

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#38]
The server terminate button on the dashboard is inactive/does not do anything?

![screen shot 2018-08-28 at 9 43 37 am](https://user-images.githubusercontent.com/14067061/44692608-04b48580-aaa7-11e8-9b3b-f3ce97157539.png)

**Comment by gweis** [comment]
fixed by enabling DELETE for CORS requests.
