### ISSUE TITLE
Configure Keycloak to enable local account registration and log in

### ISSUE THREAD

**Issue by manhinli** [ausecocloud/ecocloud#39]
Keycloak needs to be configured to enable local account registration and log in for the relevant realm.

The settings to configure:
* Realm settings
  * Login
    * User registration = ON
    * Email as username = ON

**Comment by manhinli** [comment]
This should be assigned to @gweis.

**Comment by gweis** [comment]
related to #34

**Comment by gweis** [comment]
closed in #34
