### ISSUE TITLE
Improve text in email address verification email

### ISSUE THREAD

**Issue by hoylen** [ausecocloud/ecocloud#46]
When a user registers their email address and password, they get an email sent to their email address.

1. Change the From & Reply-To address name to be "ecocloud Support" instead of just "Support".
2. Change the subject to be something like "ecocloud login registration: email address verification" instead of just "Verify email".

It would be nice to show the full verification URL in the message (in addition to making it a clickable link) for users who are security conscious and don't click on unknown links inside emails. But unfortunately, that URL is horribly long.

Any chance the Web pages can refer to the thing that the user is registering for as an "ecocloud login" instead of a "local account" or "local ecocloud account"? This is to clearly distinguish between the account and the authentication mechanism used to access the account. If someone signs in using AAF or Google, they still have a "account" created for them - the thing their workspace and servers are associated with. What users are really registering for is a login mechanism (email and password). It could be called a "Keycloak account", but that is confusing since we would be reusing the word "account" for two different concepts, and users don't need to know about Keycloak.

**Comment by gweis** [comment]
I have changed the From address header (and removed the separate reply-to address, it should use the from now as well)

James, can you check whether it's possible to change the email template?

**Comment by manhinli** [comment]
Template located at: https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/login/login-verify-email.ftl

**Comment by gweis** [comment]
I guess if it is just about the text we have to modify this here
https://github.com/ausecocloud/keycloak_theme/blob/master/theme/login/messages/messages_en.properties

**Comment by hoylen** [comment]
Probably no need to modify the text, unless you or Sarah wants it changed.

I wouldn't expand out the current URL, since it would be too ugly -- unless Keycloak can generate a shorter token.

It is fine for the alpha release.

**Comment by hoylen** [comment]
I'll close this ticket on the assumption it is now fine. I can't really test it, without finding another email address to use to create a Keycloak login.

**Comment by manhinli** [comment]
Putting this note in for future reference:

* email template and message content: https://github.com/keycloak/keycloak/tree/master/themes/src/main/resources/theme/base/email
* login/registration "verify email" page content: https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/login/login-verify-email.ftl

**Comment by manhinli** [comment]
> Any chance the Web pages can refer to the thing that the user is registering for as an "ecocloud login" instead of a "local account" or "local ecocloud account"? This is to clearly distinguish between the account and the authentication mechanism used to access the account.

I do get what you're trying to say, but we're already using the phrase "sign in" as the verb, so "sign in with your ecocloud login" feels off, considering that "login" is accepted generally as both a verb and noun.

Maybe something like "Sign in with your ecocloud ID"?

**Comment by hoylen** [comment]
"ecocloud ID" works.

My point is there are two concepts and we should not overload the same word to mean one or the other in different contexts.

The two concepts (nouns) being:
- The Keycloak thing which the user uses to authenticate: it only apples when they are not using AAF or Google.
- The common thing every user will have: it always applies, regardless of which authentication mechanism they use.

**Comment by manhinli** [comment]
> My point is there are two concepts and we should not overload the same word to mean one or the other in different contexts.
> 
> The two concepts (nouns) being:
> 
>     The Keycloak thing which the user uses to authenticate: it only apples when they are not using AAF or Google.
>     The common thing every user will have: it always applies, regardless of which authentication mechanism they use.

I did understand that - since everyone that exists on the platform has an "account/identity/user" of some sort, the problem stems from the fact that we're branding the authentication service as being part of the same thing as the application.

We'll end up just splitting hairs and becoming too technical if we do start making it "correct".
