### ISSUE TITLE
Add export to Dropbox in file context menu

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#6]
Need to ensure users are able to get their results and files out of ecocloud through dropbox

**Comment by gweis** [comment]
File context menu is not easy to implement. The JupyterLab file browser context menu can't be extended this way.

To make this work we would need to fork the JupyterLab file browser, or try to get our changes merged upstream. 

I suggest we track any UI/UX changes (even if we really want context menus) in a new ticket. Before we do this, we may want to think about how integration with other cloud storage services would look like. I.e. it may be better to build some sort of 'app / tab' (like the Launcher tab) to interact with cloud storage services.
