### ISSUE TITLE
Change snippets to only download, but not read/decode data into the environment

### ISSUE THREAD

**Issue by manhinli** [ausecocloud/ecocloud#71]
At the moment, the snippets for Python and R are reading in the content of the file into the environment, but this is causing a few headaches:
* there is no one baseline format to read into - we can't always assume it is text
* the code for R is problematic for a variety of reasons - one of which is the `getURLContent()` function which doesn't follow redirects (and bugs out when instructed to)
* snippets currently write content into the `data` variable which the user needs to be aware of in case it does overwrite their own `data`

After discussions on Friday, 9 November, we came to the conclusion that the main thing to do here is to fetch the content, and to leave the reading/decoding to the user.

This ticket is to change the snippet code to provide only the necessary code to download the files in question.

**Comment by manhinli** [comment]
Done, sent through as part of PR: https://github.com/ausecocloud/workspace-ui/pull/23

**Comment by gweis** [comment]
merged and deployed
