### ISSUE TITLE
Firefox is not loading some of the UI components correctly

### ISSUE THREAD

**Issue by sarahrichmond** [ausecocloud/ecocloud#77]
On the dashboard, it does not show that I have a server running. 

Also, when clicking on 'Launch notebook server' it does not display the config options at all.

This only happens on firefox. Chrome and Safari work as normal.

**Comment by manhinli** [comment]
This isn't affecting just Firefox; all browsers are affected. (Probably didn't pick it up due to caching)

(Firefox, Chrome, Safari)
![image](https://user-images.githubusercontent.com/3337903/51646530-9aa3fc00-1fc4-11e9-853e-334af3dbef70.png)

**Comment by manhinli** [comment]
@gweis I would suggest to have `workspace-ui` rolled back to a previous working version if that's possible while we fix this because this is a major issue.

**Comment by manhinli** [comment]
Fixed in https://github.com/ausecocloud/workspace-ui/commit/83e0c8147f1e0da6c10accb248b60782940a0317
